version: 2.1
orbs:
  node: circleci/node@4.0.0
workflows:
  node-tests:
    jobs:
      - node/test
  build-and-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build

